os: linux
sudo: false
env:
  - REQUIRED_RED_VERSION=064

install:
  - sudo apt-get install lib32ncurses5 lib32z1 libc6-i386 libcurl3
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libcurl3:i386
  - mkdir -p .local/bin
  - wget https://static.red-lang.org/dl/linux/red-${REQUIRED_RED_VERSION} -O .local/bin/red
  - chmod 755 .local/bin/red
  - export PATH="`pwd`/.local/bin:${PATH}"
  - red --version

script:
  - mkdir -p _build
  - red -r -t Linux hot.red
  - mv hot _build/hot-linux
  - red -r -t MSDOS hot.red
  - mv hot.exe _build/hot-msdos.exe
  - red -r -t Darwin hot.red
  - mv hot _build/hot-darwin

deploy:
  provider: releases
  api_key:
    - secure: "kSYpSkuELtwEK+sat+KKhPfYMGGw7vaQs6CGqzX4enmW7naRfIO48Y9cAT4qwSpSUNxEsIRwZCDnHmU4kPPjMOKUkmHOoIuWEFJujjCAtzw54G6X+r6H+OSkJmmvaflFvvHo/gJR5VnJhgDd6pc8ql+o2fxrTqHToM9arpvjjRSJCMLlz+o7IgP/6jMFquhVQIMm5OdM29yAmaTSwYrOJgKI1FSA6bty3ESTallCL9Ate7ThdBSY7+4LoxSaLZOkfYZpa1Rs+Tuotw32PuX/DOgwY/tCl7aH9v85SDMIgfoI1pcoFzk8JVIIKfKj6x2H+j3/uYcILmEWzbrTMoorJhp9p83seR7pszuKB3c0auEdu7g3XErq1nikhnfFvvxKdth9jFnNJUcTfoCSx+3U6qzdRpxPfqJFEGmKAJiHS9rNrUBx2exTrMEQpS5MRpb/x8JS16v08y8p8E7ILvWzLfKtKCPa8s53DVKzy0eiwhuggJOI2rcfoIwEE6BHVyfHi/Qh3lKo7QtDPt/1dezUQUQnjakeM5mAgMcfYFqYiQF0jJLCbjHf9qOPVku5FxzFAKlFdqhBhfLZl3kDLLPfdukXy7hJSmQpZ1PDhJt0UntmQOuDWejbf9iEtqoHOJZa9ulRik8gIGzgxcAFw49Mkp1haa1XOrzKeWI+tA3fVwk="
  file_glob: true
  file:
    - _build/hot-linux
    - _build/hot-msdos.exe
    - _build/hot-darwin
  skip_cleanup: true
  on:
    tags: true
